tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/ssl/traefik/cert.pem
        keyFile: /etc/ssl/traefik/key.pem
  certificates:
    - certFile: /etc/ssl/traefik/cert.pem
      keyFile: /etc/ssl/traefik/key.pem

http:
  routers:
    ###############################################################################################################################################################################

    ## EXTERNAL ROUTING ##
    traefik:
      entryPoints:
        - https
      rule: "Host(`traefik.$DOMAIN`)"
      service: traefik
      middlewares:
        - "traefikDashboardAuth"
        - "securityHeaders"
      tls:
        domains:
          - main: "$DOMAIN"
            sans:
              - "*.$DOMAIN"
    #Supabase Frontend routing
    supabase-studio:
      entryPoints:
        - https
      rule: "Host(`www.$DOMAIN`)"
      service: supabase-studio
      middlewares:
        - "securityHeaders"

    #Supabase Kong routing
    supabase-kong:
      entryPoints:
        - https
      rule: "Host(`studio.$DOMAIN`)"
      tls: {}
      service: supabase-kong
      middlewares:
        - "securityHeaders"

    #Supabase Analytics routing
    supabase-analytics:
      entryPoints:
        - https
      rule: "Host(`analytics.$DOMAIN`)"
      tls: {}
      service: supabase-analytics
      middlewares:
        - "securityHeaders"

########################################################################################################################################################################

  ## SERVICES ##
  services:
    # Traefik service
    traefik:
      loadBalancer:
        servers:
          - url: http://traefik:8181
    # Traefik
    traefikDashboardAuth:
      basicAuth:
        usersFile: "/etc/traefik/htpasswd"
        users:
          - "{{env $TRAEFIK_DASHBOARD_USER}}:{{env $TRAEFIK_DASHBOARD_PWD}}"

    # Supabase Frontend service
    supabase-studio:
      loadbalancer:
        servers:
          - url: "http://kong:3000"

    # Supabase Kong service
    supabase-kong:
      loadbalancer:
        servers:
          - url: "http://kong:8000"


    # Supabase Analytics service
    supabase-analytics:
      loadbalancer:
        servers:
          - url: "http://analytics:4000"


  ###############################################################################################################################################################################

  ## MIDDLEWARES ##
  middlewares:

    # Security headers
    securityHeaders:
      headers:
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex"
          server: ""
        sslProxyHeaders:
          X-Forwarded-Proto: https
        referrerPolicy: "same-origin"
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 63072000
        stsPreload: true
